"""Generate a Windows lock file for AVS runtime and development dependencies."""
from __future__ import annotations

import importlib.metadata
import sys
import tomllib
from pathlib import Path

from packaging.markers import default_environment
from packaging.requirements import Requirement
from packaging.utils import canonicalize_name


ROOT = Path(__file__).resolve().parent.parent
PYPROJECT = ROOT / "pyproject.toml"
OUTPUT = ROOT / "requirements.lock.txt"


def dependency_closure(requirements: list[str]) -> dict[str, str]:
    pending = [Requirement(item) for item in requirements]
    versions: dict[str, str] = {}
    environment = default_environment()

    while pending:
        requirement = pending.pop()
        if requirement.marker and not requirement.marker.evaluate(environment):
            continue
        name = canonicalize_name(requirement.name)
        if name in versions:
            continue
        distribution = importlib.metadata.distribution(requirement.name)
        versions[name] = distribution.version
        for child in distribution.requires or []:
            parsed = Requirement(child)
            if not parsed.marker or parsed.marker.evaluate(environment):
                pending.append(parsed)
    return versions


def main() -> int:
    data = tomllib.loads(PYPROJECT.read_text(encoding="utf-8"))
    project = data["project"]
    roots = [*project.get("dependencies", [])]
    roots.extend(project.get("optional-dependencies", {}).get("dev", []))
    versions = dependency_closure(roots)
    lines = [
        "# Generated by scripts/lock_python_deps.py; do not edit by hand.",
        f"# Target: Windows, Python {sys.version_info.major}.{sys.version_info.minor}",
        *[f"{name}=={version}" for name, version in sorted(versions.items())],
        "",
    ]
    OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"[OK] Wrote {OUTPUT.name}: {len(versions)} packages")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
